Metrics/BlockLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'spec/**/*.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/features/create_generic_work_spec.rb'
    - 'spec/features/create_audiovisual_work_spec.rb'

RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/presenters/hyrax/audiovisual_work_presenter_spec.rb'
    - 'spec/presenters/hyrax/generic_work_presenter_spec.rb'

RSpec/NamedSubject:
  Enabled: false

# Copied from Hyrax
# # By default RSpec/MessageSpies has the following:
# #   Prefer have_received for setting message expectations. Setup form as a spy using allow or instance_spy.
# # The default assumes EnforcedStyle is 'have_received'. Most of our specs are 'receive'
RSpec/MessageSpies:
  Enabled: false
